AWSTemplateFormatVersion: 2010-09-09
Description: Reusable Template for Security Group

# Define Parameters
Parameters:
  #Default VPC ID
  DefaultVPCId:
    Type: String
    Default: '' # Enter VPC ID

  WPSGName:
    Type: String
    Default: wp-security-group
  # My Network IP
  MyNetworkIP:
    Type: String
    Default: '' # Enter My Network IP
 # Required Tags
  # Team Key 
  TeamTagKey:
    Type: String
    Default: Team
  # Team Value
  TeamTagValue:
    Type: String
    Default: infra
  # Env Key
  EnvTagKey:
    Type: String
    Default: Env
  # Env Value
  EnvTagValue:
    Type: String
    Default: dev
      

# Define Resources  
Resources:
  # Wordpress Security Group
  WPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Wordpress Security Group
      GroupName: !Ref WPSGName
      VpcId: !Ref DefaultVPCId
      SecurityGroupIngress:
        - CidrIp: !Ref MyNetworkIP
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
      Tags:
        - Key: Name
          Value: !Ref WPSGName
        - Key: !Ref TeamTagKey
          Value: !Ref TeamTagValue
        - Key: !Ref EnvTagKey
          Value: !Ref EnvTagValue


# Define Outputs
Outputs:
  WPSGName:
    Description: Wordpress Security Name
    Value: !Ref WPSecurityGroup
 